### ISSUE TITLE
Django 3.1 support

### ISSUE THREAD

**Issue by ivlevdenis** [django-polymorphic/django-polymorphic#458]
Have exception after update Django version to 3.1.
`ImportError: cannot import name 'FieldDoesNotExist' from 'django.db.models'`
https://docs.djangoproject.com/en/3.1/releases/3.1/#id1

**Comment by chrisglass** [comment]
This is a know issue since django 3.X support is only on master for now - although there should be a new release soon.

If you want to help with a new release please try with master in your environment, and report back (master should work with django 3.X)
